### ISSUE TITLE
Crashing in API 25

### ISSUE THREAD

**Issue by arihant-001** [sdsmdg/liener#3]
API 25 does not allow multiple views in window manager.
![image](https://cloud.githubusercontent.com/assets/23583851/23782221/061a925c-056c-11e7-9050-4e617a1a4226.png)

**Comment by yadav-rahul** [comment]
@rahulbabbar1 What do you think about this?

**Comment by rahulbabbar1** [comment]
@yadav-rahul Can be fixed, using a custom view manager that will act as a single view for window manger, and will contain all the views.

**Comment by arihant-001** [comment]
I think we should use a library for this.
